var hierarchy =
[
    [ "AddInBase", null, [
      [ "XLToolboxForExcel.ThisAddIn", "classXLToolboxForExcel_1_1ThisAddIn.html", null ]
    ] ],
    [ "ApplicationSettingsBase", null, [
      [ "Bovender.Mvvm.Views.Settings.WindowSettings", "classBovender_1_1Mvvm_1_1Views_1_1Settings_1_1WindowSettings.html", null ],
      [ "Bovender.Mvvm.Views.Settings.WindowSettings", "classBovender_1_1Mvvm_1_1Views_1_1Settings_1_1WindowSettings.html", null ],
      [ "XLToolbox.Properties.Settings", "classXLToolbox_1_1Properties_1_1Settings.html", null ]
    ] ],
    [ "Bovender.Extensions.ArrayExtensions", "classBovender_1_1Extensions_1_1ArrayExtensions.html", null ],
    [ "XLToolbox.Backup.BackupFile", "classXLToolbox_1_1Backup_1_1BackupFile.html", null ],
    [ "XLToolbox.Test.Backup.BackupFileTest", "classXLToolbox_1_1Test_1_1Backup_1_1BackupFileTest.html", null ],
    [ "XLToolbox.Backup.Backups", "classXLToolbox_1_1Backup_1_1Backups.html", null ],
    [ "XLToolbox.Test.Backup.BackupsTest", "classXLToolbox_1_1Test_1_1Backup_1_1BackupsTest.html", null ],
    [ "XLToolbox.Test.Export.BatchExportSettingsViewModelTest", "classXLToolbox_1_1Test_1_1Export_1_1BatchExportSettingsViewModelTest.html", null ],
    [ "Bovender.Mvvm.BindingWebBrowser", "classBovender_1_1Mvvm_1_1BindingWebBrowser.html", null ],
    [ "Bovender.ExceptionHandler.CentralHandler", "classBovender_1_1ExceptionHandler_1_1CentralHandler.html", null ],
    [ "XLToolbox.Test.WorkbookStorage.ClassForTesting", "classXLToolbox_1_1Test_1_1WorkbookStorage_1_1ClassForTesting.html", null ],
    [ "XLToolbox.CmmandExtensions", "classXLToolbox_1_1CmmandExtensions.html", null ],
    [ "XLToolbox.Export.Lcms.cmsColorSpaceSignatureExtension", "classXLToolbox_1_1Export_1_1Lcms_1_1cmsColorSpaceSignatureExtension.html", null ],
    [ "XLToolbox.Test.Export.ColorProfileRepositoryViewModelTest", "classXLToolbox_1_1Test_1_1Export_1_1ColorProfileRepositoryViewModelTest.html", null ],
    [ "XLToolbox.Export.Models.ColorSpaceExtensions", "classXLToolbox_1_1Export_1_1Models_1_1ColorSpaceExtensions.html", null ],
    [ "XLToolbox.Test.Excel.ColumnHelperTest", "classXLToolbox_1_1Test_1_1Excel_1_1ColumnHelperTest.html", null ],
    [ "Bovender.CommonHelpers", "classBovender_1_1CommonHelpers.html", null ],
    [ "XLToolbox.Export.Lcms.Constants", "classXLToolbox_1_1Export_1_1Lcms_1_1Constants.html", null ],
    [ "XLToolbox.Test.Csv.CsvFileTest", "classXLToolbox_1_1Test_1_1Csv_1_1CsvFileTest.html", null ],
    [ "XLToolbox.Csv.CsvSettings", "classXLToolbox_1_1Csv_1_1CsvSettings.html", null ],
    [ "XLToolbox.Dispatcher", "classXLToolbox_1_1Dispatcher.html", null ],
    [ "Bovender.Mvvm.EnumProvider< T >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< BatchExportLayout >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< BatchExportObjects >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< BatchExportScope >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< ColorSpace >", "classBovender_1_1Mvvm_1_1EnumProvider.html", [
      [ "XLToolbox.Export.ViewModels.ColorSpaceProvider", "classXLToolbox_1_1Export_1_1ViewModels_1_1ColorSpaceProvider.html", null ]
    ] ],
    [ "Bovender.Mvvm.EnumProvider< FileType >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< Language >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.EnumProvider< Transparency >", "classBovender_1_1Mvvm_1_1EnumProvider.html", [
      [ "XLToolbox.Export.ViewModels.TransparencyProvider", "classXLToolbox_1_1Export_1_1ViewModels_1_1TransparencyProvider.html", null ]
    ] ],
    [ "Bovender.Mvvm.EnumProvider< Unit >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
    [ "Bovender.Mvvm.ViewModels.EnumViewModel< T >", "classBovender_1_1Mvvm_1_1ViewModels_1_1EnumViewModel.html", null ],
    [ "EventArgs", null, [
      [ "Bovender.ExceptionHandler.ManageExceptionEventArgs", "classBovender_1_1ExceptionHandler_1_1ManageExceptionEventArgs.html", null ],
      [ "Bovender.ExceptionHandler.ManageExceptionEventArgs", "classBovender_1_1ExceptionHandler_1_1ManageExceptionEventArgs.html", null ],
      [ "Bovender.ExceptionHandler.UploadFailedEventArgs", "classBovender_1_1ExceptionHandler_1_1UploadFailedEventArgs.html", null ],
      [ "Bovender.ExceptionHandler.UploadFailedEventArgs", "classBovender_1_1ExceptionHandler_1_1UploadFailedEventArgs.html", null ],
      [ "Bovender.Mvvm.Messaging.MessageArgs< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1MessageArgs.html", null ],
      [ "Bovender.Mvvm.Messaging.MessageArgs< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1MessageArgs.html", null ],
      [ "XLToolbox.Excel.ViewModels.InstanceShutdownEventArgs", "classXLToolbox_1_1Excel_1_1ViewModels_1_1InstanceShutdownEventArgs.html", null ],
      [ "XLToolbox.Excel.ViewModels.SelectionChangedEventArgs", "classXLToolbox_1_1Excel_1_1ViewModels_1_1SelectionChangedEventArgs.html", null ],
      [ "XLToolbox.Export.Models.BitmapCreatedEventArgs", "classXLToolbox_1_1Export_1_1Models_1_1BitmapCreatedEventArgs.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerEventArgs", "classXLToolbox_1_1SheetManager_1_1SheetManagerEventArgs.html", null ],
      [ "XLToolbox.SheetManager.TaskPaneManagerEventArgs", "classXLToolbox_1_1SheetManager_1_1TaskPaneManagerEventArgs.html", null ]
    ] ],
    [ "Exception", null, [
      [ "Bovender.ExceptionHandler.ExceptionSubmissionException", "classBovender_1_1ExceptionHandler_1_1ExceptionSubmissionException.html", null ],
      [ "Bovender.ExceptionHandler.UnexpectedResponseException", "classBovender_1_1ExceptionHandler_1_1UnexpectedResponseException.html", null ],
      [ "Bovender.ExceptionHandler.UnexpectedResponseException", "classBovender_1_1ExceptionHandler_1_1UnexpectedResponseException.html", null ],
      [ "Bovender.ExceptionHandler.UnhandledException", "classBovender_1_1ExceptionHandler_1_1UnhandledException.html", null ],
      [ "Bovender.ExceptionHandler.UnhandledException", "classBovender_1_1ExceptionHandler_1_1UnhandledException.html", null ],
      [ "Bovender.Unmanaged.DllLoadingFailedException", "classBovender_1_1Unmanaged_1_1DllLoadingFailedException.html", null ],
      [ "Bovender.Unmanaged.DllLoadingFailedException", "classBovender_1_1Unmanaged_1_1DllLoadingFailedException.html", null ],
      [ "Bovender.Unmanaged.DllNotFoundException", "classBovender_1_1Unmanaged_1_1DllNotFoundException.html", null ],
      [ "Bovender.Unmanaged.DllNotFoundException", "classBovender_1_1Unmanaged_1_1DllNotFoundException.html", null ],
      [ "Bovender.Unmanaged.DllSha1MismatchException", "classBovender_1_1Unmanaged_1_1DllSha1MismatchException.html", null ],
      [ "Bovender.Unmanaged.DllSha1MismatchException", "classBovender_1_1Unmanaged_1_1DllSha1MismatchException.html", null ],
      [ "Bovender.Versioning.DownloadCorruptException", "classBovender_1_1Versioning_1_1DownloadCorruptException.html", null ],
      [ "Bovender.Versioning.DownloadCorruptException", "classBovender_1_1Versioning_1_1DownloadCorruptException.html", null ],
      [ "Bovender.Versioning.InvalidVersionStringException", "classBovender_1_1Versioning_1_1InvalidVersionStringException.html", null ],
      [ "Bovender.Versioning.InvalidVersionStringException", "classBovender_1_1Versioning_1_1InvalidVersionStringException.html", null ],
      [ "XLToolbox.Excel.ExcelException", "classXLToolbox_1_1Excel_1_1ExcelException.html", null ],
      [ "XLToolbox.Excel.ViewModels.InvalidSheetNameException", "classXLToolbox_1_1Excel_1_1ViewModels_1_1InvalidSheetNameException.html", null ],
      [ "XLToolbox.ExceptionHandler.TestException", "classXLToolbox_1_1ExceptionHandler_1_1TestException.html", null ],
      [ "XLToolbox.Export.Models.StoreException", "classXLToolbox_1_1Export_1_1Models_1_1StoreException.html", null ],
      [ "XLToolbox.Export.TileException", "classXLToolbox_1_1Export_1_1TileException.html", null ],
      [ "XLToolbox.Export.WorkingClipboardException", "classXLToolbox_1_1Export_1_1WorkingClipboardException.html", null ],
      [ "XLToolbox.Vba.VbaException", "classXLToolbox_1_1Vba_1_1VbaException.html", null ],
      [ "XLToolbox.WorkbookStorage.WorkbookStorageException", "classXLToolbox_1_1WorkbookStorage_1_1WorkbookStorageException.html", [
        [ "XLToolbox.WorkbookStorage.EmptyKeyException", "classXLToolbox_1_1WorkbookStorage_1_1EmptyKeyException.html", null ],
        [ "XLToolbox.WorkbookStorage.InvalidContextException", "classXLToolbox_1_1WorkbookStorage_1_1InvalidContextException.html", [
          [ "XLToolbox.WorkbookStorage.UndefinedContextException", "classXLToolbox_1_1WorkbookStorage_1_1UndefinedContextException.html", null ]
        ] ],
        [ "XLToolbox.WorkbookStorage.UnkownKeyException", "classXLToolbox_1_1WorkbookStorage_1_1UnkownKeyException.html", null ]
      ] ]
    ] ],
    [ "XLToolbox.Test.Export.ExporterTest", "classXLToolbox_1_1Test_1_1Export_1_1ExporterTest.html", null ],
    [ "XLToolbox.Export.ExportFileName", "classXLToolbox_1_1Export_1_1ExportFileName.html", null ],
    [ "XLToolbox.UnitTests.Export.ExportFileNameTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1ExportFileNameTest.html", null ],
    [ "Bovender.FileHelpers", "classBovender_1_1FileHelpers.html", null ],
    [ "XLToolbox.Export.Models.FileTypeExtensions", "classXLToolbox_1_1Export_1_1Models_1_1FileTypeExtensions.html", null ],
    [ "XLToolbox.Globals", "classXLToolbox_1_1Globals.html", null ],
    [ "XLToolbox.Test.Helpers", "classXLToolbox_1_1Test_1_1Helpers.html", null ],
    [ "XLToolbox.Vba.IApi", "interfaceXLToolbox_1_1Vba_1_1IApi.html", [
      [ "XLToolbox.Vba.Api", "classXLToolbox_1_1Vba_1_1Api.html", null ]
    ] ],
    [ "ICommand", null, [
      [ "Bovender.Mvvm.DelegatingCommand", "classBovender_1_1Mvvm_1_1DelegatingCommand.html", null ],
      [ "Bovender.Mvvm.DelegatingCommand", "classBovender_1_1Mvvm_1_1DelegatingCommand.html", null ]
    ] ],
    [ "IComparable", null, [
      [ "Bovender.Versioning.SemanticVersion", "classBovender_1_1Versioning_1_1SemanticVersion.html", [
        [ "XLToolbox.Versioning.SemanticVersion", "classXLToolbox_1_1Versioning_1_1SemanticVersion.html", null ]
      ] ],
      [ "Bovender.Versioning.SemanticVersion", "classBovender_1_1Versioning_1_1SemanticVersion.html", null ],
      [ "XLToolbox.Excel.Models.RangeHelperBase", "classXLToolbox_1_1Excel_1_1Models_1_1RangeHelperBase.html", [
        [ "XLToolbox.Excel.Models.ColumnHelper", "classXLToolbox_1_1Excel_1_1Models_1_1ColumnHelper.html", null ],
        [ "XLToolbox.Excel.Models.RowHelper", "classXLToolbox_1_1Excel_1_1Models_1_1RowHelper.html", null ]
      ] ]
    ] ],
    [ "IComponentConnector", null, [
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvFileView", "classXLToolbox_1_1Csv_1_1CsvFileView.html", null ],
      [ "XLToolbox.Csv.CsvFileView", "classXLToolbox_1_1Csv_1_1CsvFileView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.WindowDownloadUpdate", "classXLToolbox_1_1WindowDownloadUpdate.html", null ],
      [ "XLToolbox.WindowDownloadUpdate", "classXLToolbox_1_1WindowDownloadUpdate.html", null ],
      [ "XLToolboxForExcel.Splash", "classXLToolboxForExcel_1_1Splash.html", null ]
    ] ],
    [ "IDataErrorInfo", null, [
      [ "Bovender.Mvvm.Messaging.StringMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1StringMessageContent.html", [
        [ "Bovender.Mvvm.Messaging.FileNameMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1FileNameMessageContent.html", null ],
        [ "Bovender.Mvvm.Messaging.FileNameMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1FileNameMessageContent.html", null ]
      ] ],
      [ "Bovender.Mvvm.Messaging.StringMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1StringMessageContent.html", null ],
      [ "XLToolbox.Keyboard.ShortcutViewModel", "classXLToolbox_1_1Keyboard_1_1ShortcutViewModel.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsViewModel", "classXLToolbox_1_1UserSettings_1_1UserSettingsViewModel.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "Bovender.Unmanaged.DllManager", "classBovender_1_1Unmanaged_1_1DllManager.html", null ],
      [ "Bovender.Unmanaged.DllManager", "classBovender_1_1Unmanaged_1_1DllManager.html", null ],
      [ "XLToolbox.Excel.Models.Reference", "classXLToolbox_1_1Excel_1_1Models_1_1Reference.html", null ],
      [ "XLToolbox.Excel.ViewModels.Instance", "classXLToolbox_1_1Excel_1_1ViewModels_1_1Instance.html", null ],
      [ "XLToolbox.Excel.ViewModels.SelectionViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1SelectionViewModel.html", null ],
      [ "XLToolbox.Excel.ViewModels.SheetViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1SheetViewModel.html", null ],
      [ "XLToolbox.Export.DibBitmap", "classXLToolbox_1_1Export_1_1DibBitmap.html", null ],
      [ "XLToolbox.Export.Exporter", "classXLToolbox_1_1Export_1_1Exporter.html", null ],
      [ "XLToolbox.Export.Models.TiledBitmap", "classXLToolbox_1_1Export_1_1Models_1_1TiledBitmap.html", null ],
      [ "XLToolbox.Export.WorkingClipboard", "classXLToolbox_1_1Export_1_1WorkingClipboard.html", null ],
      [ "XLToolbox.Legacy.LegacyToolbox", "classXLToolbox_1_1Legacy_1_1LegacyToolbox.html", null ],
      [ "XLToolbox.WorkbookStorage.Store", "classXLToolbox_1_1WorkbookStorage_1_1Store.html", null ],
      [ "XLToolboxForExcel.ThisAddIn", "classXLToolboxForExcel_1_1ThisAddIn.html", null ]
    ] ],
    [ "Bovender.Mvvm.Messaging.IMessage< T >", "interfaceBovender_1_1Mvvm_1_1Messaging_1_1IMessage.html", null ],
    [ "Bovender.Mvvm.Messaging.IMessage< T >", "interfaceBovender_1_1Mvvm_1_1Messaging_1_1IMessage.html", [
      [ "Bovender.Mvvm.Messaging.Message< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
      [ "Bovender.Mvvm.Messaging.Message< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ]
    ] ],
    [ "INotifyPropertyChanged", null, [
      [ "Bovender.Mvvm.EnumProvider< T >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
      [ "Bovender.Mvvm.EnumProvider< T >", "classBovender_1_1Mvvm_1_1EnumProvider.html", null ],
      [ "Bovender.Mvvm.ViewModels.ViewModelBase", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelBase.html", [
        [ "Bovender.ExceptionHandler.ExceptionViewModel", "classBovender_1_1ExceptionHandler_1_1ExceptionViewModel.html", [
          [ "XLToolbox.ExceptionHandler.ExceptionViewModel", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionViewModel.html", null ]
        ] ],
        [ "Bovender.ExceptionHandler.ExceptionViewModel", "classBovender_1_1ExceptionHandler_1_1ExceptionViewModel.html", null ],
        [ "Bovender.HtmlFiles.HtmlFileViewModel", "classBovender_1_1HtmlFiles_1_1HtmlFileViewModel.html", null ],
        [ "Bovender.HtmlFiles.HtmlFileViewModel", "classBovender_1_1HtmlFiles_1_1HtmlFileViewModel.html", null ],
        [ "Bovender.Mvvm.Messaging.MessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1MessageContent.html", [
          [ "Bovender.Mvvm.Messaging.StringMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1StringMessageContent.html", null ],
          [ "Bovender.Mvvm.Messaging.StringMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1StringMessageContent.html", null ],
          [ "Bovender.Mvvm.Messaging.ViewModelMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1ViewModelMessageContent.html", [
            [ "Bovender.Mvvm.Messaging.ProcessMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1ProcessMessageContent.html", null ],
            [ "Bovender.Mvvm.Messaging.ProcessMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1ProcessMessageContent.html", null ]
          ] ],
          [ "Bovender.Mvvm.Messaging.ViewModelMessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1ViewModelMessageContent.html", null ]
        ] ],
        [ "Bovender.Mvvm.Messaging.MessageContent", "classBovender_1_1Mvvm_1_1Messaging_1_1MessageContent.html", null ],
        [ "Bovender.Mvvm.ViewModels.EnumViewModel< T >", "classBovender_1_1Mvvm_1_1ViewModels_1_1EnumViewModel.html", null ],
        [ "Bovender.Mvvm.ViewModels.EnumViewModel< T >", "classBovender_1_1Mvvm_1_1ViewModels_1_1EnumViewModel.html", null ],
        [ "Bovender.UserSettings.UserSettingsExceptionViewModel", "classBovender_1_1UserSettings_1_1UserSettingsExceptionViewModel.html", null ],
        [ "Bovender.UserSettings.UserSettingsExceptionViewModel", "classBovender_1_1UserSettings_1_1UserSettingsExceptionViewModel.html", null ],
        [ "Bovender.UserSettings.UserSettingsViewModel", "classBovender_1_1UserSettings_1_1UserSettingsViewModel.html", null ],
        [ "Bovender.UserSettings.UserSettingsViewModel", "classBovender_1_1UserSettings_1_1UserSettingsViewModel.html", null ],
        [ "Bovender.Versioning.UpdaterViewModel", "classBovender_1_1Versioning_1_1UpdaterViewModel.html", [
          [ "XLToolbox.Versioning.UpdaterViewModel", "classXLToolbox_1_1Versioning_1_1UpdaterViewModel.html", null ]
        ] ],
        [ "Bovender.Versioning.UpdaterViewModel", "classBovender_1_1Versioning_1_1UpdaterViewModel.html", null ],
        [ "XLToolbox.About.AboutViewModel", "classXLToolbox_1_1About_1_1AboutViewModel.html", [
          [ "XLToolbox.Greeter.GreeterViewModel", "classXLToolbox_1_1Greeter_1_1GreeterViewModel.html", null ]
        ] ],
        [ "XLToolbox.Backup.BackupFailedViewModel", "classXLToolbox_1_1Backup_1_1BackupFailedViewModel.html", null ],
        [ "XLToolbox.Backup.BackupFileViewModel", "classXLToolbox_1_1Backup_1_1BackupFileViewModel.html", null ],
        [ "XLToolbox.Backup.BackupsViewModel", "classXLToolbox_1_1Backup_1_1BackupsViewModel.html", null ],
        [ "XLToolbox.Excel.ViewModels.ChartViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1ChartViewModel.html", null ],
        [ "XLToolbox.Excel.ViewModels.Instance", "classXLToolbox_1_1Excel_1_1ViewModels_1_1Instance.html", null ],
        [ "XLToolbox.Excel.ViewModels.SelectionViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1SelectionViewModel.html", null ],
        [ "XLToolbox.Excel.ViewModels.SheetViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1SheetViewModel.html", null ],
        [ "XLToolbox.Excel.ViewModels.WorkbookViewModel", "classXLToolbox_1_1Excel_1_1ViewModels_1_1WorkbookViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.ColorProfileRepositoryViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1ColorProfileRepositoryViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.ColorProfileViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1ColorProfileViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.PresetsRepositoryViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1PresetsRepositoryViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.PresetViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1PresetViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.ScreenshotExporterViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1ScreenshotExporterViewModel.html", null ],
        [ "XLToolbox.Keyboard.ManagerViewModel", "classXLToolbox_1_1Keyboard_1_1ManagerViewModel.html", null ],
        [ "XLToolbox.Keyboard.ShortcutViewModel", "classXLToolbox_1_1Keyboard_1_1ShortcutViewModel.html", null ],
        [ "XLToolbox.Logging.LogFileViewModel", "classXLToolbox_1_1Logging_1_1LogFileViewModel.html", null ],
        [ "XLToolbox.UserSettings.UserSettingsViewModel", "classXLToolbox_1_1UserSettings_1_1UserSettingsViewModel.html", null ]
      ] ],
      [ "Bovender.Mvvm.ViewModels.ViewModelBase", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelBase.html", null ]
    ] ],
    [ "XLToolbox.Test.Excel.InstanceTest", "classXLToolbox_1_1Test_1_1Excel_1_1InstanceTest.html", null ],
    [ "InternalTypeHelper", null, [
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "classXamlGeneratedNamespace_1_1GeneratedInternalTypeHelper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "classXamlGeneratedNamespace_1_1GeneratedInternalTypeHelper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "classXamlGeneratedNamespace_1_1GeneratedInternalTypeHelper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "classXamlGeneratedNamespace_1_1GeneratedInternalTypeHelper.html", null ],
      [ "XamlGeneratedNamespace.GeneratedInternalTypeHelper", "classXamlGeneratedNamespace_1_1GeneratedInternalTypeHelper.html", null ]
    ] ],
    [ "IRibbonExtensibility", null, [
      [ "XLToolboxForExcel.Ribbon", "classXLToolboxForExcel_1_1Ribbon.html", null ]
    ] ],
    [ "IValueConverter", null, [
      [ "Bovender.Mvvm.Converters.BooleanNegationConverter", "classBovender_1_1Mvvm_1_1Converters_1_1BooleanNegationConverter.html", null ],
      [ "Bovender.Mvvm.Converters.BooleanNegationConverter", "classBovender_1_1Mvvm_1_1Converters_1_1BooleanNegationConverter.html", null ],
      [ "Bovender.Mvvm.Converters.EnumBooleanConverter", "classBovender_1_1Mvvm_1_1Converters_1_1EnumBooleanConverter.html", null ],
      [ "Bovender.Mvvm.Converters.EnumBooleanConverter", "classBovender_1_1Mvvm_1_1Converters_1_1EnumBooleanConverter.html", null ],
      [ "Bovender.Mvvm.Converters.SimpleExceptionConverter", "classBovender_1_1Mvvm_1_1Converters_1_1SimpleExceptionConverter.html", null ],
      [ "Bovender.Mvvm.Converters.SimpleExceptionConverter", "classBovender_1_1Mvvm_1_1Converters_1_1SimpleExceptionConverter.html", null ],
      [ "Bovender.Mvvm.Converters.VisibilityBooleanConverter", "classBovender_1_1Mvvm_1_1Converters_1_1VisibilityBooleanConverter.html", null ],
      [ "Bovender.Mvvm.Converters.VisibilityBooleanConverter", "classBovender_1_1Mvvm_1_1Converters_1_1VisibilityBooleanConverter.html", null ]
    ] ],
    [ "IWin32Window", null, [
      [ "Bovender.Win32Window", "classBovender_1_1Win32Window.html", null ]
    ] ],
    [ "XLToolbox.Jumper", "classXLToolbox_1_1Jumper.html", null ],
    [ "XLToolbox.Test.JumperTest", "classXLToolbox_1_1Test_1_1JumperTest.html", null ],
    [ "LogFile", null, [
      [ "XLToolbox.Logging.LogFile", "classXLToolbox_1_1Logging_1_1LogFile.html", null ]
    ] ],
    [ "XLToolbox.Keyboard.Manager", "classXLToolbox_1_1Keyboard_1_1Manager.html", null ],
    [ "XLToolbox.Test.Keyboard.ManagerTest", "classXLToolbox_1_1Test_1_1Keyboard_1_1ManagerTest.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< Bovender.Mvvm.Messaging.ProcessMessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< FileNameMessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< MessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< ProcessMessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< StringMessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Messaging.Message< ViewModelMessageContent >", "classBovender_1_1Mvvm_1_1Messaging_1_1Message.html", null ],
    [ "Bovender.Mvvm.Actions.MessageActionExtensions", "classBovender_1_1Mvvm_1_1Actions_1_1MessageActionExtensions.html", null ],
    [ "Bovender.Mvvm.Messaging.MessageArgs< T >", "classBovender_1_1Mvvm_1_1Messaging_1_1MessageArgs.html", null ],
    [ "Bovender.Text.Multiline", "classBovender_1_1Text_1_1Multiline.html", null ],
    [ "Object", null, [
      [ "Bovender.Unmanaged.DllManager", "classBovender_1_1Unmanaged_1_1DllManager.html", null ],
      [ "Bovender.Unmanaged.DllManager", "classBovender_1_1Unmanaged_1_1DllManager.html", null ],
      [ "Bovender.Versioning.SemanticVersion", "classBovender_1_1Versioning_1_1SemanticVersion.html", null ],
      [ "Bovender.Versioning.SemanticVersion", "classBovender_1_1Versioning_1_1SemanticVersion.html", null ]
    ] ],
    [ "Bovender.Extensions.ObjectExtensions", "classBovender_1_1Extensions_1_1ObjectExtensions.html", null ],
    [ "ObservableCollection", null, [
      [ "Bovender.Mvvm.ViewModels.ViewModelCollection< TModel, TViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", null ],
      [ "Bovender.Mvvm.ViewModels.ViewModelCollection< TModel, TViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", null ]
    ] ],
    [ "Bovender.PathHelpers", "classBovender_1_1PathHelpers.html", null ],
    [ "Bovender.Unmanaged.Pinvoke", "classBovender_1_1Unmanaged_1_1Pinvoke.html", null ],
    [ "XLToolbox.Export.Models.Preset", "classXLToolbox_1_1Export_1_1Models_1_1Preset.html", null ],
    [ "XLToolbox.Export.Models.PresetsRepository", "classXLToolbox_1_1Export_1_1Models_1_1PresetsRepository.html", null ],
    [ "XLToolbox.UnitTests.Export.PresetsRepositoryTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1PresetsRepositoryTest.html", null ],
    [ "XLToolbox.UnitTests.Export.PresetsRepositoryViewModelTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1PresetsRepositoryViewModelTest.html", null ],
    [ "XLToolbox.UnitTests.Export.PresetsViewModelTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1PresetsViewModelTest.html", null ],
    [ "XLToolbox.Test.Export.PresetTest", "classXLToolbox_1_1Test_1_1Export_1_1PresetTest.html", null ],
    [ "ProcessModel", null, [
      [ "XLToolbox.Csv.CsvFileBase", "classXLToolbox_1_1Csv_1_1CsvFileBase.html", [
        [ "XLToolbox.Csv.CsvExporter", "classXLToolbox_1_1Csv_1_1CsvExporter.html", null ],
        [ "XLToolbox.Csv.CsvImporter", "classXLToolbox_1_1Csv_1_1CsvImporter.html", null ]
      ] ],
      [ "XLToolbox.Export.BatchExporter", "classXLToolbox_1_1Export_1_1BatchExporter.html", null ],
      [ "XLToolbox.Export.Exporter", "classXLToolbox_1_1Export_1_1Exporter.html", null ]
    ] ],
    [ "ProcessViewModelBase", null, [
      [ "XLToolbox.Csv.CsvExportViewModel", "classXLToolbox_1_1Csv_1_1CsvExportViewModel.html", null ],
      [ "XLToolbox.Csv.CsvImportViewModel", "classXLToolbox_1_1Csv_1_1CsvImportViewModel.html", null ],
      [ "XLToolbox.Export.ViewModels.SettingsViewModelBase", "classXLToolbox_1_1Export_1_1ViewModels_1_1SettingsViewModelBase.html", [
        [ "XLToolbox.Export.ViewModels.BatchExportSettingsViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1BatchExportSettingsViewModel.html", null ],
        [ "XLToolbox.Export.ViewModels.SingleExportSettingsViewModel", "classXLToolbox_1_1Export_1_1ViewModels_1_1SingleExportSettingsViewModel.html", null ]
      ] ]
    ] ],
    [ "XLToolbox.HelpSystem.Provider", "classXLToolbox_1_1HelpSystem_1_1Provider.html", null ],
    [ "XLToolbox.Export.QuickExporter", "classXLToolbox_1_1Export_1_1QuickExporter.html", null ],
    [ "XLToolbox.Test.Excel.ReferenceTest", "classXLToolbox_1_1Test_1_1Excel_1_1ReferenceTest.html", null ],
    [ "ReleaseInfo", null, [
      [ "XLToolbox.Versioning.ReleaseInfo", "classXLToolbox_1_1Versioning_1_1ReleaseInfo.html", null ]
    ] ],
    [ "ReleaseInfoViewModel", null, [
      [ "XLToolbox.Versioning.ReleaseInfoViewModel", "classXLToolbox_1_1Versioning_1_1ReleaseInfoViewModel.html", null ]
    ] ],
    [ "XLToolbox.Test.Excel.RowHelperTest", "classXLToolbox_1_1Test_1_1Excel_1_1RowHelperTest.html", null ],
    [ "XLToolbox.Export.ScreenshotExporter", "classXLToolbox_1_1Export_1_1ScreenshotExporter.html", null ],
    [ "XLToolbox.Test.Export.ScreenShotExporterTest", "classXLToolbox_1_1Test_1_1Export_1_1ScreenShotExporterTest.html", null ],
    [ "XLToolbox.UnitTests.Excel.SelectionViewModelTest", "classXLToolbox_1_1UnitTests_1_1Excel_1_1SelectionViewModelTest.html", null ],
    [ "XLToolbox.Export.Models.Settings", "classXLToolbox_1_1Export_1_1Models_1_1Settings.html", [
      [ "XLToolbox.Export.Models.BatchExportSettings", "classXLToolbox_1_1Export_1_1Models_1_1BatchExportSettings.html", null ],
      [ "XLToolbox.Export.Models.SingleExportSettings", "classXLToolbox_1_1Export_1_1Models_1_1SingleExportSettings.html", null ]
    ] ],
    [ "XLToolbox.SheetManager.SheetManagerTaskPane", "classXLToolbox_1_1SheetManager_1_1SheetManagerTaskPane.html", null ],
    [ "XLToolbox.Test.Excel.SheetViewModelTest", "classXLToolbox_1_1Test_1_1Excel_1_1SheetViewModelTest.html", null ],
    [ "XLToolbox.Keyboard.Shortcut", "classXLToolbox_1_1Keyboard_1_1Shortcut.html", null ],
    [ "XLToolbox.Test.Keyboard.ShortcutTest", "classXLToolbox_1_1Test_1_1Keyboard_1_1ShortcutTest.html", null ],
    [ "XLToolbox.UnitTests.Export.SingleExportSettingsViewModelTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1SingleExportSettingsViewModelTest.html", null ],
    [ "XLToolbox.Test.WorkbookStorage.StoreTest", "classXLToolbox_1_1Test_1_1WorkbookStorage_1_1StoreTest.html", null ],
    [ "Bovender.Extensions.StringExtensions", "classBovender_1_1Extensions_1_1StringExtensions.html", null ],
    [ "XLToolbox.Strings", "classXLToolbox_1_1Strings.html", null ],
    [ "XLToolbox.SheetManager.TaskPaneManager", "classXLToolbox_1_1SheetManager_1_1TaskPaneManager.html", null ],
    [ "XLToolbox.Backup.TimeStamp", "classXLToolbox_1_1Backup_1_1TimeStamp.html", null ],
    [ "XLToolbox.Test.Backup.TimeStampTest", "classXLToolbox_1_1Test_1_1Backup_1_1TimeStampTest.html", null ],
    [ "TriggerAction", null, [
      [ "Bovender.Mvvm.Actions.MessageActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1MessageActionBase.html", [
        [ "Bovender.Mvvm.Actions.FileFolderActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1FileFolderActionBase.html", [
          [ "Bovender.Mvvm.Actions.ChooseFolderAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFolderAction.html", null ],
          [ "Bovender.Mvvm.Actions.ChooseFolderAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFolderAction.html", null ],
          [ "Bovender.Mvvm.Actions.FileDialogActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1FileDialogActionBase.html", [
            [ "Bovender.Mvvm.Actions.ChooseFileOpenAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFileOpenAction.html", null ],
            [ "Bovender.Mvvm.Actions.ChooseFileOpenAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFileOpenAction.html", null ],
            [ "Bovender.Mvvm.Actions.ChooseFileSaveAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFileSaveAction.html", null ],
            [ "Bovender.Mvvm.Actions.ChooseFileSaveAction", "classBovender_1_1Mvvm_1_1Actions_1_1ChooseFileSaveAction.html", null ]
          ] ],
          [ "Bovender.Mvvm.Actions.FileDialogActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1FileDialogActionBase.html", null ]
        ] ],
        [ "Bovender.Mvvm.Actions.FileFolderActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1FileFolderActionBase.html", null ],
        [ "Bovender.Mvvm.Actions.NotificationAction", "classBovender_1_1Mvvm_1_1Actions_1_1NotificationAction.html", [
          [ "Bovender.Mvvm.Actions.ConfirmationAction", "classBovender_1_1Mvvm_1_1Actions_1_1ConfirmationAction.html", null ],
          [ "Bovender.Mvvm.Actions.ConfirmationAction", "classBovender_1_1Mvvm_1_1Actions_1_1ConfirmationAction.html", null ],
          [ "XLToolbox.ExceptionHandler.SubmissionProcessAction", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessAction.html", null ],
          [ "XLToolbox.Mvvm.Actions.StringMessageAction", "classXLToolbox_1_1Mvvm_1_1Actions_1_1StringMessageAction.html", [
            [ "XLToolbox.Mvvm.Actions.ShowHtmlAction", "classXLToolbox_1_1Mvvm_1_1Actions_1_1ShowHtmlAction.html", null ]
          ] ]
        ] ],
        [ "Bovender.Mvvm.Actions.NotificationAction", "classBovender_1_1Mvvm_1_1Actions_1_1NotificationAction.html", null ],
        [ "Bovender.Mvvm.Actions.ProcessCompletedAction", "classBovender_1_1Mvvm_1_1Actions_1_1ProcessCompletedAction.html", [
          [ "XLToolbox.ExceptionHandler.SubmissionCompletedAction", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionCompletedAction.html", null ]
        ] ],
        [ "Bovender.Mvvm.Actions.ProcessCompletedAction", "classBovender_1_1Mvvm_1_1Actions_1_1ProcessCompletedAction.html", null ],
        [ "Bovender.Mvvm.Actions.ShowViewAction", "classBovender_1_1Mvvm_1_1Actions_1_1ShowViewAction.html", [
          [ "Bovender.Mvvm.Actions.ProcessAction", "classBovender_1_1Mvvm_1_1Actions_1_1ProcessAction.html", null ],
          [ "Bovender.Mvvm.Actions.ProcessAction", "classBovender_1_1Mvvm_1_1Actions_1_1ProcessAction.html", null ],
          [ "Bovender.Mvvm.Actions.ShowViewDialogAction", "classBovender_1_1Mvvm_1_1Actions_1_1ShowViewDialogAction.html", null ],
          [ "Bovender.Mvvm.Actions.ShowViewDialogAction", "classBovender_1_1Mvvm_1_1Actions_1_1ShowViewDialogAction.html", null ]
        ] ],
        [ "Bovender.Mvvm.Actions.ShowViewAction", "classBovender_1_1Mvvm_1_1Actions_1_1ShowViewAction.html", null ],
        [ "XLToolbox.Mvvm.Actions.ChooseFolderAction", "classXLToolbox_1_1Mvvm_1_1Actions_1_1ChooseFolderAction.html", null ]
      ] ],
      [ "Bovender.Mvvm.Actions.MessageActionBase", "classBovender_1_1Mvvm_1_1Actions_1_1MessageActionBase.html", null ]
    ] ],
    [ "TriggerBase", null, [
      [ "Bovender.Mvvm.Actions.NonUiTrigger", "classBovender_1_1Mvvm_1_1Actions_1_1NonUiTrigger.html", null ],
      [ "Bovender.Mvvm.Actions.NonUiTrigger", "classBovender_1_1Mvvm_1_1Actions_1_1NonUiTrigger.html", null ]
    ] ],
    [ "XLToolbox.Export.Models.UnitsExtensions", "classXLToolbox_1_1Export_1_1Models_1_1UnitsExtensions.html", null ],
    [ "XLToolbox.UnitTests.Export.UnitTest", "classXLToolbox_1_1UnitTests_1_1Export_1_1UnitTest.html", null ],
    [ "Bovender.Versioning.Updater", "classBovender_1_1Versioning_1_1Updater.html", [
      [ "XLToolbox.Versioning.Updater", "classXLToolbox_1_1Versioning_1_1Updater.html", null ]
    ] ],
    [ "UserControl", null, [
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.Backup.BackupsDisclaimer", "classXLToolbox_1_1Backup_1_1BackupsDisclaimer.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerControl", "classXLToolbox_1_1SheetManager_1_1SheetManagerControl.html", null ]
    ] ],
    [ "Bovender.UserSettings.UserSettingsBase", "classBovender_1_1UserSettings_1_1UserSettingsBase.html", [
      [ "XLToolbox.UserSettings.UserSettings", "classXLToolbox_1_1UserSettings_1_1UserSettings.html", null ]
    ] ],
    [ "Bovender.Mvvm.ViewModels.ViewModelCollection< TModel, TViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", null ],
    [ "Bovender.Mvvm.ViewModels.ViewModelCollection< BackupFile, BackupFileViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", [
      [ "XLToolbox.Backup.BackupFilesCollection", "classXLToolbox_1_1Backup_1_1BackupFilesCollection.html", null ]
    ] ],
    [ "Bovender.Mvvm.ViewModels.ViewModelCollection< Preset, PresetViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", [
      [ "XLToolbox.Export.ViewModels.PresetViewModelCollection", "classXLToolbox_1_1Export_1_1ViewModels_1_1PresetViewModelCollection.html", null ]
    ] ],
    [ "Bovender.Mvvm.ViewModels.ViewModelCollection< Shortcut, ShortcutViewModel >", "classBovender_1_1Mvvm_1_1ViewModels_1_1ViewModelCollection.html", [
      [ "XLToolbox.Keyboard.ShortcutViewModelCollection", "classXLToolbox_1_1Keyboard_1_1ShortcutViewModelCollection.html", null ]
    ] ],
    [ "Window", null, [
      [ "Bovender.Mvvm.Views.ConfirmationView", "classBovender_1_1Mvvm_1_1Views_1_1ConfirmationView.html", null ],
      [ "Bovender.Mvvm.Views.ConfirmationView", "classBovender_1_1Mvvm_1_1Views_1_1ConfirmationView.html", null ],
      [ "Bovender.Mvvm.Views.ProcessView", "classBovender_1_1Mvvm_1_1Views_1_1ProcessView.html", null ],
      [ "Bovender.Mvvm.Views.ProcessView", "classBovender_1_1Mvvm_1_1Views_1_1ProcessView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.About.AboutView", "classXLToolbox_1_1About_1_1AboutView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupFailedView", "classXLToolbox_1_1Backup_1_1BackupFailedView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Backup.BackupsView", "classXLToolbox_1_1Backup_1_1BackupsView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvExportView", "classXLToolbox_1_1Csv_1_1CsvExportView.html", null ],
      [ "XLToolbox.Csv.CsvFileView", "classXLToolbox_1_1Csv_1_1CsvFileView.html", null ],
      [ "XLToolbox.Csv.CsvFileView", "classXLToolbox_1_1Csv_1_1CsvFileView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Csv.CsvImportView", "classXLToolbox_1_1Csv_1_1CsvImportView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.PropertiesView", "classXLToolbox_1_1Excel_1_1Views_1_1PropertiesView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.Excel.Views.QuitView", "classXLToolbox_1_1Excel_1_1Views_1_1QuitView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionDetailView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionDetailView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.ExceptionView", "classXLToolbox_1_1ExceptionHandler_1_1ExceptionView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionFailureView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionFailureView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionProcessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionProcessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.ExceptionHandler.SubmissionSuccessView", "classXLToolbox_1_1ExceptionHandler_1_1SubmissionSuccessView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.BatchExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1BatchExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.PresetsRepositoryView", "classXLToolbox_1_1Export_1_1Views_1_1PresetsRepositoryView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Export.Views.SingleExportSettingsView", "classXLToolbox_1_1Export_1_1Views_1_1SingleExportSettingsView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Greeter.GreeterView", "classXLToolbox_1_1Greeter_1_1GreeterView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ManagerView", "classXLToolbox_1_1Keyboard_1_1ManagerView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Keyboard.ShortcutView", "classXLToolbox_1_1Keyboard_1_1ShortcutView.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingDisabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingDisabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Logging.IncompleteShutdownLoggingEnabled", "classXLToolbox_1_1Logging_1_1IncompleteShutdownLoggingEnabled.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.HtmlFileView", "classXLToolbox_1_1Mvvm_1_1Views_1_1HtmlFileView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.StringMessageContentView", "classXLToolbox_1_1Mvvm_1_1Views_1_1StringMessageContentView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.Mvvm.Views.UserSettingsExceptionView", "classXLToolbox_1_1Mvvm_1_1Views_1_1UserSettingsExceptionView.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.SheetManager.SheetManagerWindow", "classXLToolbox_1_1SheetManager_1_1SheetManagerWindow.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.UserSettings.UserSettingsView", "classXLToolbox_1_1UserSettings_1_1UserSettingsView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.InstallUpdateView", "classXLToolbox_1_1Versioning_1_1InstallUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.NotAuthorizedForUpdateView", "classXLToolbox_1_1Versioning_1_1NotAuthorizedForUpdateView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdateAvailableView", "classXLToolbox_1_1Versioning_1_1UpdateAvailableView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.Versioning.UpdaterProcessView", "classXLToolbox_1_1Versioning_1_1UpdaterProcessView.html", null ],
      [ "XLToolbox.WindowDownloadUpdate", "classXLToolbox_1_1WindowDownloadUpdate.html", null ],
      [ "XLToolbox.WindowDownloadUpdate", "classXLToolbox_1_1WindowDownloadUpdate.html", null ],
      [ "XLToolboxForExcel.Splash", "classXLToolboxForExcel_1_1Splash.html", null ]
    ] ],
    [ "Window", null, [
      [ "Bovender.Mvvm.Views.NotificationView", "classBovender_1_1Mvvm_1_1Views_1_1NotificationView.html", null ],
      [ "Bovender.Mvvm.Views.NotificationView", "classBovender_1_1Mvvm_1_1Views_1_1NotificationView.html", null ]
    ] ],
    [ "Bovender.Extensions.WindowExtensions", "classBovender_1_1Extensions_1_1WindowExtensions.html", null ],
    [ "Bovender.Mvvm.Views.Settings.WindowState", "classBovender_1_1Mvvm_1_1Views_1_1Settings_1_1WindowState.html", null ],
    [ "XLToolbox.Excel.Extensions.WorkbookExtension", "classXLToolbox_1_1Excel_1_1Extensions_1_1WorkbookExtension.html", null ],
    [ "XLToolbox.Excel.Models.WorkbookProperty", "classXLToolbox_1_1Excel_1_1Models_1_1WorkbookProperty.html", null ],
    [ "XLToolbox.Test.Excel.WorkbookViewModelTest", "classXLToolbox_1_1Test_1_1Excel_1_1WorkbookViewModelTest.html", null ],
    [ "Bovender.WpfHelpers", "classBovender_1_1WpfHelpers.html", null ]
];