//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLToolbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLToolbox.RibbonStrings", typeof(RibbonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this add-in.
        /// </summary>
        internal static string ButtonAboutLabel {
            get {
                return ResourceManager.GetString("ButtonAboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the XL Toolbox version, license, and credits.
        /// </summary>
        internal static string ButtonAboutSupertip {
            get {
                return ResourceManager.GetString("ButtonAboutSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string ButtonCheckForUpdateLabel {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if an update to the XL Toolbox addin is available..
        /// </summary>
        internal static string ButtonCheckForUpdateSupertip {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdateSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Export.
        /// </summary>
        internal static string ButtonExportBatchLabel {
            get {
                return ResourceManager.GetString("ButtonExportBatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all graphical objects on this worksheet or in the current workbook using the last settings..
        /// </summary>
        internal static string ButtonExportBatchSupertip {
            get {
                return ResourceManager.GetString("ButtonExportBatchSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selection.
        /// </summary>
        internal static string ButtonExportSelectionLabel {
            get {
                return ResourceManager.GetString("ButtonExportSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the currently selected graphical object(s) using the last settings.
        /// </summary>
        internal static string ButtonExportSelectionSupertip {
            get {
                return ResourceManager.GetString("ButtonExportSelectionSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ButtonExportSettingsLabel {
            get {
                return ResourceManager.GetString("ButtonExportSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit settings for graphic export..
        /// </summary>
        internal static string ButtonExportSettingsSupertip {
            get {
                return ResourceManager.GetString("ButtonExportSettingsSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Export.
        /// </summary>
        internal static string GroupExportLabel {
            get {
                return ResourceManager.GetString("GroupExportLabel", resourceCulture);
            }
        }
    }
}
