//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLToolbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLToolbox.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Daniel&apos;s XL Toolbox.
        /// </summary>
        public static string AboutXLToolbox {
            get {
                return ResourceManager.GetString("AboutXLToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action requires a selection of cells..
        /// </summary>
        public static string ActionRequiresSelectionOfCells {
            get {
                return ResourceManager.GetString("ActionRequiresSelectionOfCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active worksheet.
        /// </summary>
        public static string ActiveSheet {
            get {
                return ResourceManager.GetString("ActiveSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active workbook.
        /// </summary>
        public static string ActiveWorkbook {
            get {
                return ResourceManager.GetString("ActiveWorkbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All open workbooks.
        /// </summary>
        public static string AllOpenWorkbooks {
            get {
                return ResourceManager.GetString("AllOpenWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % ALT.
        /// </summary>
        public static string AltModifier {
            get {
                return ResourceManager.GetString("AltModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-in is distributed under the Apache License, Version 2.0, on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License..
        /// </summary>
        public static string ApacheDisclaimer {
            get {
                return ResourceManager.GetString("ApacheDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me.
        /// </summary>
        public static string AskMe {
            get {
                return ResourceManager.GetString("AskMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask me as needed.
        /// </summary>
        public static string AskMeAsNeeded {
            get {
                return ResourceManager.GetString("AskMeAsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands.
        /// </summary>
        public static string AvailableCommands {
            get {
                return ResourceManager.GetString("AvailableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export.
        /// </summary>
        public static string BatchExport {
            get {
                return ResourceManager.GetString("BatchExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bovender framework.
        /// </summary>
        public static string BovenderFramework {
            get {
                return ResourceManager.GetString("BovenderFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All graphic objects.
        /// </summary>
        public static string ChartsAndShapes {
            get {
                return ResourceManager.GetString("ChartsAndShapes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only charts.
        /// </summary>
        public static string ChartsOnly {
            get {
                return ResourceManager.GetString("ChartsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose where to save the update file.
        /// </summary>
        public static string ChooseWhereToSaveUpdateFile {
            get {
                return ResourceManager.GetString("ChooseWhereToSaveUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR version.
        /// </summary>
        public static string ClrVersion {
            get {
                return ResourceManager.GetString("ClrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMYK.
        /// </summary>
        public static string Cmyk {
            get {
                return ResourceManager.GetString("Cmyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color management.
        /// </summary>
        public static string ColorManagement {
            get {
                return ResourceManager.GetString("ColorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color profile.
        /// </summary>
        public static string ColorProfile {
            get {
                return ResourceManager.GetString("ColorProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color space.
        /// </summary>
        public static string ColorSpace {
            get {
                return ResourceManager.GetString("ColorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command:.
        /// </summary>
        public static string CommandColon {
            get {
                return ResourceManager.GetString("CommandColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public comment (optional).
        /// </summary>
        public static string CommentOptional {
            get {
                return ResourceManager.GetString("CommentOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this preset?.
        /// </summary>
        public static string ConfirmRemovePreset {
            get {
                return ResourceManager.GetString("ConfirmRemovePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy statement: The technical details will be published in the bug tracker online. Your name and e-mail (both optional) will ONLY be sent to the developer and NOT be shared. If you enter a comment below, the COMMENT WILL BE PUBLISHED anonymously along with the technical data online..
        /// </summary>
        public static string CrashReportPrivacy {
            get {
                return ResourceManager.GetString("CrashReportPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV export failed.
        /// </summary>
        public static string CsvExportFailed {
            get {
                return ResourceManager.GetString("CsvExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during CSV export.
        ///
        ///The following message was received:.
        /// </summary>
        public static string CsvExportFailedMessage {
            get {
                return ResourceManager.GetString("CsvExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Settings.
        /// </summary>
        public static string CsvSettings {
            get {
                return ResourceManager.GetString("CsvSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^ CTRL.
        /// </summary>
        public static string CtrlModifier {
            get {
                return ResourceManager.GetString("CtrlModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^+{PgUp} CTRL SHIFT PAGE-UP.
        /// </summary>
        public static string CtrlShiftPgUp {
            get {
                return ResourceManager.GetString("CtrlShiftPgUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current log:.
        /// </summary>
        public static string CurrentLogColon {
            get {
                return ResourceManager.GetString("CurrentLogColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data analysis and visualization for Excel, for free..
        /// </summary>
        public static string DataAnalysisAndVisualizationForExcelForFree {
            get {
                return ResourceManager.GetString("DataAnalysisAndVisualizationForExcelForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal separator.
        /// </summary>
        public static string DecimalSeparator {
            get {
                return ResourceManager.GetString("DecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default settings will be used..
        /// </summary>
        public static string DefaultUserSettingsWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultUserSettingsWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard all.
        /// </summary>
        public static string DiscardAll {
            get {
                return ResourceManager.GetString("DiscardAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded file cannot be installed because it is different from the official update file. This can be caused by errors in the network connection, a faulty disk drive on your computer, or by someone hampering with the update process. The update will not be installed..
        /// </summary>
        public static string DownloadedFileCannotBeInstalled {
            get {
                return ResourceManager.GetString("DownloadedFileCannotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading XL Toolbox update.
        /// </summary>
        public static string DownloadingXLToolboxUpdate {
            get {
                return ResourceManager.GetString("DownloadingXLToolboxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download URL is:.
        /// </summary>
        public static string DownloadUrlIs {
            get {
                return ResourceManager.GetString("DownloadUrlIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete? This operation cannot be undone..
        /// </summary>
        public static string DoYouReallyWantToDeleteCannotBeUndone {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable logging now?.
        /// </summary>
        public static string DoYouWantToEnableLogging {
            get {
                return ResourceManager.GetString("DoYouWantToEnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do want to examine the log files now?.
        /// </summary>
        public static string DoYouWantToExamineLogs {
            get {
                return ResourceManager.GetString("DoYouWantToExamineLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit export preset.
        /// </summary>
        public static string EditExportPreset {
            get {
                return ResourceManager.GetString("EditExportPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit keyboard shortcuts.
        /// </summary>
        public static string EditKeyboardShortcuts {
            get {
                return ResourceManager.GetString("EditKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit legacy Toolbox preferences.
        /// </summary>
        public static string EditLegacyToolboxPreferences {
            get {
                return ResourceManager.GetString("EditLegacyToolboxPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit keyboard shortcut.
        /// </summary>
        public static string EditShortcut {
            get {
                return ResourceManager.GetString("EditShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail (optional).
        /// </summary>
        public static string EMailOptional {
            get {
                return ResourceManager.GetString("EMailOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMF files (*.emf).
        /// </summary>
        public static string EmfFiles {
            get {
                return ResourceManager.GetString("EmfFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XL Toolbox keyboard shortcuts.
        /// </summary>
        public static string EnableKeyboardShortcuts {
            get {
                return ResourceManager.GetString("EnableKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Logging.
        /// </summary>
        public static string EnableLogging {
            get {
                return ResourceManager.GetString("EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable XL Toolbox keyboard shortcuts.
        /// </summary>
        public static string EnableShortcuts {
            get {
                return ResourceManager.GetString("EnableShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the desired new sheet name (1-31 characters, must not contain any of : [] /\ *?.
        /// </summary>
        public static string EnterNewSheetName {
            get {
                return ResourceManager.GetString("EnterNewSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while downloading the file:
        ///
        ///&quot;{0}&quot;.
        ///
        ///You may want to try again..
        /// </summary>
        public static string ErrorOccurredWhileDownloading {
            get {
                return ResourceManager.GetString("ErrorOccurredWhileDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel bitness.
        /// </summary>
        public static string ExcelBitness {
            get {
                return ResourceManager.GetString("ExcelBitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel version.
        /// </summary>
        public static string ExcelVersion {
            get {
                return ResourceManager.GetString("ExcelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Report Submission.
        /// </summary>
        public static string ExceptionReportSubmission {
            get {
                return ResourceManager.GetString("ExceptionReportSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit crash report..
        /// </summary>
        public static string ExceptionReportSubmissionFailed {
            get {
                return ResourceManager.GetString("ExceptionReportSubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV file.
        /// </summary>
        public static string ExportCsvFile {
            get {
                return ResourceManager.GetString("ExportCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed.
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during export.
        ///
        ///The following error message was received:.
        /// </summary>
        public static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch the current version information from the internet.
        ///The error was:
        ///{0}
        ///
        ///Is your internet connection working?.
        /// </summary>
        public static string FetchingVersionInformationFailed {
            get {
                return ResourceManager.GetString("FetchingVersionInformationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field separator.
        /// </summary>
        public static string FieldSeparator {
            get {
                return ResourceManager.GetString("FieldSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name template.
        /// </summary>
        public static string FileNameTemplate {
            get {
                return ResourceManager.GetString("FileNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {workbook}, {worksheet} and {index} as placeholders. File extension can be omitted. Target directory will be queried when you click &quot;Export&quot;..
        /// </summary>
        public static string FileNameTemplateHint {
            get {
                return ResourceManager.GetString("FileNameTemplateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeImage version.
        /// </summary>
        public static string FreeImageVersion {
            get {
                return ResourceManager.GetString("FreeImageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details..
        /// </summary>
        public static string GplDisclaimer {
            get {
                return ResourceManager.GetString("GplDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grays.
        /// </summary>
        public static string GrayScale {
            get {
                return ResourceManager.GetString("GrayScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Use \t to separate fields by tabs..
        /// </summary>
        public static string HintUseBackslashT {
            get {
                return ResourceManager.GetString("HintUseBackslashT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you want to quit?.
        /// </summary>
        public static string HowDoYouWantToQuit {
            get {
                return ResourceManager.GetString("HowDoYouWantToQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are the owner of this computer, you can download the update manually, then right-click the update installer and choose &quot;Run as administrator&quot; to acquire appropriate permissions to install..
        /// </summary>
        public static string IfYouAreTheOwnerOfThisComputer {
            get {
                return ResourceManager.GetString("IfYouAreTheOwnerOfThisComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you suspect that this could have been caused by a malfunction of the add-in, you may want to turn on the technical logging. The log file contents may be helpful in troubleshooting the issue..
        /// </summary>
        public static string IfYouSuspect {
            get {
                return ResourceManager.GetString("IfYouSuspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size: {0:0.00} megapixels/{1:0.00} MB uncompressed..
        /// </summary>
        public static string ImageSizeMegaPixels {
            get {
                return ResourceManager.GetString("ImageSizeMegaPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV file.
        /// </summary>
        public static string ImportCsvFile {
            get {
                return ResourceManager.GetString("ImportCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete shutdown detected.
        /// </summary>
        public static string IncompleteShutdown {
            get {
                return ResourceManager.GetString("IncompleteShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner message.
        /// </summary>
        public static string InnerMessage {
            get {
                return ResourceManager.GetString("InnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Invalid key sequence.).
        /// </summary>
        public static string InvalidKeySequence {
            get {
                return ResourceManager.GetString("InvalidKeySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Toolbox preferences.
        /// </summary>
        public static string LegacyPreferences {
            get {
                return ResourceManager.GetString("LegacyPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsolete XL Toolbox version found.
        /// </summary>
        public static string LegacyToolboxDetectedCaption {
            get {
                return ResourceManager.GetString("LegacyToolboxDetectedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An obsolete version of the XL Toolbox was found. It will be deactivated now. You can use old XL Toolbox commands in the new, Next-Generation version. You may want to uninstall the old version from your system using &quot;Add/Remove Software&quot;..
        /// </summary>
        public static string LegacyToolboxDetectedMessage {
            get {
                return ResourceManager.GetString("LegacyToolboxDetectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already enabled logging. The log files may contain technical information that helps to identify the problem. Please consider sending the current log file to support@xltoolbox.net..
        /// </summary>
        public static string LoggingWasEnabled {
            get {
                return ResourceManager.GetString("LoggingWasEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys:.
        /// </summary>
        public static string ModifierKeysColon {
            get {
                return ResourceManager.GetString("ModifierKeysColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black &amp; white.
        /// </summary>
        public static string Monochrome {
            get {
                return ResourceManager.GetString("Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (optional).
        /// </summary>
        public static string NameOptional {
            get {
                return ResourceManager.GetString("NameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the XL Toolbox is available for download..
        /// </summary>
        public static string NewVersionAvailableForDownload {
            get {
                return ResourceManager.GetString("NewVersionAvailableForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized to update.
        /// </summary>
        public static string NotAuthorizedToUpdate {
            get {
                return ResourceManager.GetString("NotAuthorizedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No warranties ‒ see license..
        /// </summary>
        public static string NoWarrantiesSeeLicense {
            get {
                return ResourceManager.GetString("NoWarrantiesSeeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open workbooks.
        /// </summary>
        public static string OpenWorkbooks {
            get {
                return ResourceManager.GetString("OpenWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS bitness.
        /// </summary>
        public static string OSBitness {
            get {
                return ResourceManager.GetString("OSBitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version.
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a crash report by clicking the button below. If you give your name and e-mail, the developer may contact you when trying to solve the problem. Click &quot;Technical information...&quot; to view the contents of the bug report..
        /// </summary>
        public static string PleaseSendCrashReport {
            get {
                return ResourceManager.GetString("PleaseSendCrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG files (*.png).
        /// </summary>
        public static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve aspect ratio.
        /// </summary>
        public static string PreserveAspectRatio {
            get {
                return ResourceManager.GetString("PreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve layout on sheet.
        /// </summary>
        public static string PreserveLayout {
            get {
                return ResourceManager.GetString("PreserveLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Excel, discarding changes.
        /// </summary>
        public static string QuitDiscardingChanges {
            get {
                return ResourceManager.GetString("QuitDiscardingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Excel.
        /// </summary>
        public static string QuitExcel {
            get {
                return ResourceManager.GetString("QuitExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Excel, saving all changed workbooks.
        /// </summary>
        public static string QuitSavingChanges {
            get {
                return ResourceManager.GetString("QuitSavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range selection required.
        /// </summary>
        public static string RangeSelectionRequired {
            get {
                return ResourceManager.GetString("RangeSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove preset.
        /// </summary>
        public static string RemovePreset {
            get {
                return ResourceManager.GetString("RemovePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to submit the report..
        /// </summary>
        public static string ReportNotSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ReportNotSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report was successfully submitted..
        /// </summary>
        public static string ReportSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ReportSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart Excel for the changes to take effect..
        /// </summary>
        public static string RestartForChangesToTakeEffect {
            get {
                return ResourceManager.GetString("RestartForChangesToTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string Rgb {
            get {
                return ResourceManager.GetString("Rgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot-Quality Export.
        /// </summary>
        public static string ScreenshotExport {
            get {
                return ResourceManager.GetString("ScreenshotExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The screenshot-quality export works with graphical objects only. Please select a graphic (chart or shape)..
        /// </summary>
        public static string ScreenshotExportRequiresGraphic {
            get {
                return ResourceManager.GetString("ScreenshotExportRequiresGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send crash report.
        /// </summary>
        public static string SendCrashReport {
            get {
                return ResourceManager.GetString("SendCrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string SendingEllipsis {
            get {
                return ResourceManager.GetString("SendingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit the error report.
        ///The following error occurred:
        ///{0}.
        /// </summary>
        public static string SendingErrorReportFailed {
            get {
                return ResourceManager.GetString("SendingErrorReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error report was successfully submitted..
        /// </summary>
        public static string SendingErrorReportSuccessful {
            get {
                return ResourceManager.GetString("SendingErrorReportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a copy of the e-mail to the developer.
        /// </summary>
        public static string SendMeACopy {
            get {
                return ResourceManager.GetString("SendMeACopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings and log folder.
        /// </summary>
        public static string SettingsAndLogFolder {
            get {
                return ResourceManager.GetString("SettingsAndLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + SHIFT.
        /// </summary>
        public static string ShiftModifier {
            get {
                return ResourceManager.GetString("ShiftModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More help on shortcuts (Microsoft website).
        /// </summary>
        public static string ShortcutsHelp {
            get {
                return ResourceManager.GetString("ShortcutsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single graphic export.
        /// </summary>
        public static string SingleGraphicExport {
            get {
                return ResourceManager.GetString("SingleGraphicExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual items.
        /// </summary>
        public static string SingleItems {
            get {
                return ResourceManager.GetString("SingleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the XL Toolbox features still reside in the &apos;legacy&apos; add-in (prior to version 7); you can access their preferences here..
        /// </summary>
        public static string SomeFeaturesAreContainedInLegacyAddin {
            get {
                return ResourceManager.GetString("SomeFeaturesAreContainedInLegacyAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {F1}, {PgUp}, ... Special keys.
        /// </summary>
        public static string SpecialKeys {
            get {
                return ResourceManager.GetString("SpecialKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting report.
        /// </summary>
        public static string SubmittingReport {
            get {
                return ResourceManager.GetString("SubmittingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SVG files.
        /// </summary>
        public static string SvgFiles {
            get {
                return ResourceManager.GetString("SvgFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the task pane.
        /// </summary>
        public static string TaskPaneWidth {
            get {
                return ResourceManager.GetString("TaskPaneWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is technically not possible to automatically store the current width of the task pane during shutdown and restore it the next time. However, the initial value here always represents the current task pane width if the worksheet manager is open..
        /// </summary>
        public static string TaskPaneWidthCannotBeAutomaticallySaved {
            get {
                return ResourceManager.GetString("TaskPaneWidthCannotBeAutomaticallySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information.
        /// </summary>
        public static string TechnicalInformation {
            get {
                return ResourceManager.GetString("TechnicalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information....
        /// </summary>
        public static string TechnicalInformationEllipsis {
            get {
                return ResourceManager.GetString("TechnicalInformationEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is free software..
        /// </summary>
        public static string ThisIsFreeSoftware {
            get {
                return ResourceManager.GetString("ThisIsFreeSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the error message:.
        /// </summary>
        public static string ThisIsTheErrorMessage {
            get {
                return ResourceManager.GetString("ThisIsTheErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is version:.
        /// </summary>
        public static string ThisIsVersion {
            get {
                return ResourceManager.GetString("ThisIsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands separator.
        /// </summary>
        public static string ThousandsSeparator {
            get {
                return ResourceManager.GetString("ThousandsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF files (*.tif).
        /// </summary>
        public static string TifFiles {
            get {
                return ResourceManager.GetString("TifFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent canvas.
        /// </summary>
        public static string TransparentCanvas {
            get {
                return ResourceManager.GetString("TransparentCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves the canvas transparent. If the graphics object (e.g. the chart) that is exported contains white background color, the transparency will not be evident. In this case, if you want transparency, choose &quot;Transparent white&quot;..
        /// </summary>
        public static string TransparentCanvasTooltip {
            get {
                return ResourceManager.GetString("TransparentCanvasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent white.
        /// </summary>
        public static string TransparentWhite {
            get {
                return ResourceManager.GetString("TransparentWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces all whites in the image file to become transparent..
        /// </summary>
        public static string TransparentWhiteTooltip {
            get {
                return ResourceManager.GetString("TransparentWhiteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access the windows clipboard, is another program using it?
        ///
        ///Error message:
        ///
        ///{0}.
        /// </summary>
        public static string UnableToAccessClipboard {
            get {
                return ResourceManager.GetString("UnableToAccessClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved workbooks.
        /// </summary>
        public static string UnsavedWorkbooks {
            get {
                return ResourceManager.GetString("UnsavedWorkbooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update has been successfully downloaded and will be installed when you quit Excel..
        /// </summary>
        public static string UpdateHasBeenDownloaded {
            get {
                return ResourceManager.GetString("UpdateHasBeenDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update that you downloaded earlier will be installed now..
        /// </summary>
        public static string UpdateWillBeInstalledNow {
            get {
                return ResourceManager.GetString("UpdateWillBeInstalledNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use color management.
        /// </summary>
        public static string UseColorManagement {
            get {
                return ResourceManager.GetString("UseColorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal XL Toolbox settings could not be loaded..
        /// </summary>
        public static string UserSettingsCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("UserSettingsCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionParametrized {
            get {
                return ResourceManager.GetString("VersionParametrized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the XL Toolbox add-in!.
        /// </summary>
        public static string WelcomeToXLToolbox {
            get {
                return ResourceManager.GetString("WelcomeToXLToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White canvas.
        /// </summary>
        public static string WhiteCanvas {
            get {
                return ResourceManager.GetString("WhiteCanvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paints the graphic object on a white canvas without transparency..
        /// </summary>
        public static string WhiteCanvasTooltip {
            get {
                return ResourceManager.GetString("WhiteCanvasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workbook.
        /// </summary>
        public static string Workbook {
            get {
                return ResourceManager.GetString("Workbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worksheet.
        /// </summary>
        public static string Worksheet {
            get {
                return ResourceManager.GetString("Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet Manager.
        /// </summary>
        public static string WorksheetManager {
            get {
                return ResourceManager.GetString("WorksheetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox Error!.
        /// </summary>
        public static string XLToolboxError {
            get {
                return ResourceManager.GetString("XLToolboxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox License.
        /// </summary>
        public static string XLToolboxLicense {
            get {
                return ResourceManager.GetString("XLToolboxLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that the XL Toolbox add-in was not shut down properly..
        /// </summary>
        public static string XLToolboxNotShutDownProperly {
            get {
                return ResourceManager.GetString("XLToolboxNotShutDownProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniel&apos;s XL Toolbox Update.
        /// </summary>
        public static string XLToolboxUpdate {
            get {
                return ResourceManager.GetString("XLToolboxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox version.
        /// </summary>
        public static string XLToolboxVersion {
            get {
                return ResourceManager.GetString("XLToolboxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, you do not have write permissions to the folder that the XL Toolbox add-in was installed. Therefore you will not be able to automatically update this add-in. Please ask your system administrator to perform the update for you..
        /// </summary>
        public static string YouDoNotHaveWritePermissionsUpdate {
            get {
                return ResourceManager.GetString("YouDoNotHaveWritePermissionsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have:.
        /// </summary>
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version of the XL Toolbox. No update available at this time..
        /// </summary>
        public static string YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voluntary payment (&apos;donation&apos;) is greatly appreciated. To donate, click the button below..
        /// </summary>
        public static string YourVoluntaryPaymentIsAppreciated {
            get {
                return ResourceManager.GetString("YourVoluntaryPaymentIsAppreciated", resourceCulture);
            }
        }
    }
}
