//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLToolbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLToolbox.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Daniel&apos;s XL Toolbox.
        /// </summary>
        public static string AboutXLToolbox {
            get {
                return ResourceManager.GetString("AboutXLToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        public static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose where to save the update file.
        /// </summary>
        public static string ChooseWhereToSaveUpdateFile {
            get {
                return ResourceManager.GetString("ChooseWhereToSaveUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear form.
        /// </summary>
        public static string ClearForm {
            get {
                return ResourceManager.GetString("ClearForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR version.
        /// </summary>
        public static string ClrVersion {
            get {
                return ResourceManager.GetString("ClrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public comment (optional).
        /// </summary>
        public static string CommentOptional {
            get {
                return ResourceManager.GetString("CommentOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy statement: The technical details will be published in the bug tracker online. Your name and e-mail (both optional) will ONLY be sent to the developer and NOT be shared. If you enter a comment below, the COMMENT WILL BE PUBLISHED anonymously along with the technical data online..
        /// </summary>
        public static string CrashReportPrivacy {
            get {
                return ResourceManager.GetString("CrashReportPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data analysis and visualization for Excel, for free..
        /// </summary>
        public static string DataAnalysisAndVisualizationForExcelForFree {
            get {
                return ResourceManager.GetString("DataAnalysisAndVisualizationForExcelForFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Down {
            get {
                return ResourceManager.GetString("Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded file cannot be installed because it is different from the official update file. This can be caused by errors in the network connection, a faulty disk drive on your computer, or by someone hampering with the update process. The update will not be installed..
        /// </summary>
        public static string DownloadedFileCannotBeInstalled {
            get {
                return ResourceManager.GetString("DownloadedFileCannotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading XL Toolbox update.
        /// </summary>
        public static string DownloadingXLToolboxUpdate {
            get {
                return ResourceManager.GetString("DownloadingXLToolboxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download now.
        /// </summary>
        public static string DownloadNow {
            get {
                return ResourceManager.GetString("DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download URL is:.
        /// </summary>
        public static string DownloadUrlIs {
            get {
                return ResourceManager.GetString("DownloadUrlIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail (optional).
        /// </summary>
        public static string EMailOptional {
            get {
                return ResourceManager.GetString("EMailOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel bitness.
        /// </summary>
        public static string ExcelBitness {
            get {
                return ResourceManager.GetString("ExcelBitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel version.
        /// </summary>
        public static string ExcelVersion {
            get {
                return ResourceManager.GetString("ExcelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch the current version information from the internet.
        ///The error was:
        ///{0}
        ///
        ///Is your internet connection working?.
        /// </summary>
        public static string FetchingVersionInformationFailed {
            get {
                return ResourceManager.GetString("FetchingVersionInformationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeImage version.
        /// </summary>
        public static string FreeImageVersion {
            get {
                return ResourceManager.GetString("FreeImageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are the owner of this computer, you can download the update manually, then right-click the update installer and choose &quot;Run as administrator&quot; to acquire appropriate permissions to install..
        /// </summary>
        public static string IfYouAreTheOwnerOfThisComputer {
            get {
                return ResourceManager.GetString("IfYouAreTheOwnerOfThisComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception.
        /// </summary>
        public static string InnerException {
            get {
                return ResourceManager.GetString("InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner message.
        /// </summary>
        public static string InnerMessage {
            get {
                return ResourceManager.GetString("InnerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (optional).
        /// </summary>
        public static string NameOptional {
            get {
                return ResourceManager.GetString("NameOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the XL Toolbox is available for download..
        /// </summary>
        public static string NewVersionAvailableForDownload {
            get {
                return ResourceManager.GetString("NewVersionAvailableForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized to update.
        /// </summary>
        public static string NotAuthorizedToUpdate {
            get {
                return ResourceManager.GetString("NotAuthorizedToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS bitness.
        /// </summary>
        public static string OSBitness {
            get {
                return ResourceManager.GetString("OSBitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS version.
        /// </summary>
        public static string OSVersion {
            get {
                return ResourceManager.GetString("OSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send a crash report by clicking the button below. If you give your name and e-mail, the developer may contact you when trying to solve the problem. Click &quot;Technical information...&quot; to view the contents of the bug report..
        /// </summary>
        public static string PleaseSendCrashReport {
            get {
                return ResourceManager.GetString("PleaseSendCrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send crash report.
        /// </summary>
        public static string SendCrashReport {
            get {
                return ResourceManager.GetString("SendCrashReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string SendingEllipsis {
            get {
                return ResourceManager.GetString("SendingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to submit the error report.
        ///The following error occurred:
        ///{0}.
        /// </summary>
        public static string SendingErrorReportFailed {
            get {
                return ResourceManager.GetString("SendingErrorReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error report was successfully submitted..
        /// </summary>
        public static string SendingErrorReportSuccessful {
            get {
                return ResourceManager.GetString("SendingErrorReportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me a copy of the e-mail to the developer.
        /// </summary>
        public static string SendMeACopy {
            get {
                return ResourceManager.GetString("SendMeACopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information.
        /// </summary>
        public static string TechnicalInformation {
            get {
                return ResourceManager.GetString("TechnicalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical information....
        /// </summary>
        public static string TechnicalInformationEllipsis {
            get {
                return ResourceManager.GetString("TechnicalInformationEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is free software..
        /// </summary>
        public static string ThisIsFreeSoftware {
            get {
                return ResourceManager.GetString("ThisIsFreeSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is version {0}..
        /// </summary>
        public static string ThisIsVersion {
            get {
                return ResourceManager.GetString("ThisIsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update has been successfully downloaded and will be installed when you quit Excel. To install it at a later time, click &quot;Cancel&quot;.
        ///You can find the installer in {0}..
        /// </summary>
        public static string UpdateHasBeenDownloaded {
            get {
                return ResourceManager.GetString("UpdateHasBeenDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update that you downloaded earlier will be installed now..
        /// </summary>
        public static string UpdateWillBeInstalledNow {
            get {
                return ResourceManager.GetString("UpdateWillBeInstalledNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionParametrized {
            get {
                return ResourceManager.GetString("VersionParametrized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the XL Toolbox add-in!.
        /// </summary>
        public static string WelcomeToXLToolbox {
            get {
                return ResourceManager.GetString("WelcomeToXLToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheet Manager.
        /// </summary>
        public static string WorksheetManager {
            get {
                return ResourceManager.GetString("WorksheetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox Error!.
        /// </summary>
        public static string XLToolboxError {
            get {
                return ResourceManager.GetString("XLToolboxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox License.
        /// </summary>
        public static string XLToolboxLicense {
            get {
                return ResourceManager.GetString("XLToolboxLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XL Toolbox version.
        /// </summary>
        public static string XLToolboxVersion {
            get {
                return ResourceManager.GetString("XLToolboxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, you do not have write permissions to the folder that the XL Toolbox add-in was installed. Therefore you will not be able to automatically update this add-in. Please ask your system administrator to perform the update for you..
        /// </summary>
        public static string YouDoNotHaveWritePermissionsUpdate {
            get {
                return ResourceManager.GetString("YouDoNotHaveWritePermissionsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have:.
        /// </summary>
        public static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version of the XL Toolbox. No update available at this time..
        /// </summary>
        public static string YouHaveTheLatestVersion {
            get {
                return ResourceManager.GetString("YouHaveTheLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your voluntary payment (&apos;donation&apos;) is greatly appreciated. To donate, click the button below..
        /// </summary>
        public static string YourVoluntaryPaymentIsAppreciated {
            get {
                return ResourceManager.GetString("YourVoluntaryPaymentIsAppreciated", resourceCulture);
            }
        }
    }
}
