//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XLToolbox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RibbonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RibbonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XLToolbox.RibbonStrings", typeof(RibbonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this add-in.
        /// </summary>
        internal static string ButtonAboutLabel {
            get {
                return ResourceManager.GetString("ButtonAboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about the XL Toolbox version, license, and credits.
        /// </summary>
        internal static string ButtonAboutSupertip {
            get {
                return ResourceManager.GetString("ButtonAboutSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        internal static string ButtonCheckForUpdateLabel {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if an update to the XL Toolbox addin is available..
        /// </summary>
        internal static string ButtonCheckForUpdateSupertip {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdateSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is disabled because an update operation is pending..
        /// </summary>
        internal static string ButtonCheckForUpdateSupertipDisabled {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdateSupertipDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string ButtonDonateLabel {
            get {
                return ResourceManager.GetString("ButtonDonateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a voluntary payment if you find this add-in useful..
        /// </summary>
        internal static string ButtonDonateSupertip {
            get {
                return ResourceManager.GetString("ButtonDonateSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch export with settings....
        /// </summary>
        internal static string ButtonExportBatchLabel {
            get {
                return ResourceManager.GetString("ButtonExportBatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Export.
        /// </summary>
        internal static string ButtonExportBatchQuickLabel {
            get {
                return ResourceManager.GetString("ButtonExportBatchQuickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform the last batch export again..
        /// </summary>
        internal static string ButtonExportBatchQuickSupertip {
            get {
                return ResourceManager.GetString("ButtonExportBatchQuickSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all graphical objects on this worksheet or in the current workbook using detailed settings..
        /// </summary>
        internal static string ButtonExportBatchSupertip {
            get {
                return ResourceManager.GetString("ButtonExportBatchSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string ButtonExportScreenshotLabel {
            get {
                return ResourceManager.GetString("ButtonExportScreenshotLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the current selection in screenshot quality..
        /// </summary>
        internal static string ButtonExportScreenshotSupertip {
            get {
                return ResourceManager.GetString("ButtonExportScreenshotSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export with settings....
        /// </summary>
        internal static string ButtonExportSelectionLabel {
            get {
                return ResourceManager.GetString("ButtonExportSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export selection.
        /// </summary>
        internal static string ButtonExportSelectionQuickLabel {
            get {
                return ResourceManager.GetString("ButtonExportSelectionQuickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the currently selected graphical object(s) using the last settings.
        /// </summary>
        internal static string ButtonExportSelectionQuickSupertip {
            get {
                return ResourceManager.GetString("ButtonExportSelectionQuickSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the currently selected graphical object(s) by indicating desired settings..
        /// </summary>
        internal static string ButtonExportSelectionSupertip {
            get {
                return ResourceManager.GetString("ButtonExportSelectionSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ButtonExportSettingsLabel {
            get {
                return ResourceManager.GetString("ButtonExportSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and edit settings for graphic export..
        /// </summary>
        internal static string ButtonExportSettingsSupertip {
            get {
                return ResourceManager.GetString("ButtonExportSettingsSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CSV....
        /// </summary>
        internal static string ButtonOpenCsvLabel {
            get {
                return ResourceManager.GetString("ButtonOpenCsvLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CSV file using the last import settings..
        /// </summary>
        internal static string ButtonOpenCsvSupertip {
            get {
                return ResourceManager.GetString("ButtonOpenCsvSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CSV with params....
        /// </summary>
        internal static string ButtonOpenCsvWithParamsLabel {
            get {
                return ResourceManager.GetString("ButtonOpenCsvWithParamsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the parameters and open a CSV file..
        /// </summary>
        internal static string ButtonOpenCsvWithParamsSupertip {
            get {
                return ResourceManager.GetString("ButtonOpenCsvWithParamsSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Excel.
        /// </summary>
        internal static string ButtonQuitExcelLabel {
            get {
                return ResourceManager.GetString("ButtonQuitExcelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Excel, closing all workbooks with prompts to save changes..
        /// </summary>
        internal static string ButtonQuitExcelSupertip {
            get {
                return ResourceManager.GetString("ButtonQuitExcelSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSV....
        /// </summary>
        internal static string ButtonSaveCsvLabel {
            get {
                return ResourceManager.GetString("ButtonSaveCsvLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSV file using the last export settings..
        /// </summary>
        internal static string ButtonSaveCsvSupertip {
            get {
                return ResourceManager.GetString("ButtonSaveCsvSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save CSV with params....
        /// </summary>
        internal static string ButtonSaveCsvWithParamsLabel {
            get {
                return ResourceManager.GetString("ButtonSaveCsvWithParamsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the parameters and save a CSV file..
        /// </summary>
        internal static string ButtonSaveCsvWithParamsSupertip {
            get {
                return ResourceManager.GetString("ButtonSaveCsvWithParamsSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksheets.
        /// </summary>
        internal static string ButtonSheetListLabel {
            get {
                return ResourceManager.GetString("ButtonSheetListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage worksheets..
        /// </summary>
        internal static string ButtonSheetListSupertip {
            get {
                return ResourceManager.GetString("ButtonSheetListSupertip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic Export.
        /// </summary>
        internal static string GroupExportLabel {
            get {
                return ResourceManager.GetString("GroupExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Flow.
        /// </summary>
        internal static string GroupWorkflowLabel {
            get {
                return ResourceManager.GetString("GroupWorkflowLabel", resourceCulture);
            }
        }
    }
}
